title: AnitoCrosshatch
logo: /assets/img/AClogo.png
description: A 3D Editor Tool for Cross Hatch Rendered 3D Environments.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  owner_url: https://github.com/Zerithe/CrossHatchEditor
  owner_name: Pencilheads
  repository_url: https://github.com/Zerithe/CrossHatchEditor
  zip_url: https://github.com/Zerithe/CrossHatchEditor
  tar_url: https://github.com/Zerithe/CrossHatchEditor
  repository_nwo: https://github.com/Zerithe
